import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#09090b",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Often desired for app-like feel
};

import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/components/auth-provider";
import { BottomNav } from "@/components/BottomNav";
import { getWallets } from "@/services/wallet.service";
import { Navbar } from "@/components/Navbar";
import { Shell } from "@/components/Shell";
import { AddTransactionDialog } from "@/components/AddTransactionDialog";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";
import { GlobalAddTransactionButton } from "@/components/GlobalAddTransactionButton";

import { Toaster } from "@/components/ui/sonner";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let wallets = [];
  try {
    wallets = await getWallets();
  } catch (error) {
    console.error("Failed to fetch wallets in RootLayout:", error);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-muted/40`}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Shell>
                  <Navbar /> {/* Now MobileHeader */}
                  <main className="flex-1 p-4 md:p-6 lg:p-8 pt-0 md:pt-6 pb-20 md:pb-6 bg-zinc-50 dark:bg-zinc-950 overflow-x-hidden">
                      {children}
                  </main>
            </Shell>
            <BottomNav wallets={wallets} />
            
            <GlobalAddTransactionButton wallets={wallets} />
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
